import { isSupabaseConfigured, supabase } from '@/src/lib/supabase';
import type { CalendarEvent, GalleryItem, Lead } from '@/src/types/models';

const ensureConfig = () => { if (!isSupabaseConfigured) throw new Error('Configura EXPO_PUBLIC_SUPABASE_URL y EXPO_PUBLIC_SUPABASE_ANON_KEY en .env.'); };
export async function getLeads() { ensureConfig(); const { data, error } = await supabase.from('leads').select('*').order('created_at', { ascending: false }); if (error) throw error; return (data ?? []) as Lead[]; }
export async function updateLeadPrice(id: string, finalPrice: number) { ensureConfig(); const { error } = await supabase.from('leads').update({ final_price: finalPrice }).eq('id', id); if (error) throw error; }
export async function getEvents() { ensureConfig(); const { data, error } = await supabase.from('calendar_events').select('*, leads(*)').order('start_time', { ascending: true }); if (error) throw error; return (data ?? []) as CalendarEvent[]; }
export async function getGallery() { ensureConfig(); const { data, error } = await supabase.from('gallery').select('*').order('created_at', { ascending: false }); if (error) throw error; return (data ?? []) as GalleryItem[]; }
export async function setGalleryPublic(id: string, isPublic: boolean) { ensureConfig(); const { error } = await supabase.from('gallery').update({ is_public: isPublic }).eq('id', id); if (error) throw error; }
export async function deleteGalleryItem(item: GalleryItem) { ensureConfig(); if (item.path) { const { error: storageError } = await supabase.storage.from('gallery').remove([item.path]); if (storageError) throw storageError; } const { error } = await supabase.from('gallery').delete().eq('id', item.id); if (error) throw error; }
export async function uploadGallery(uri: string, mimeType = 'image/jpeg') { ensureConfig(); const response = await fetch(uri); const file = await response.arrayBuffer(); const ext = mimeType.split('/')[1] || 'jpg'; const path = `${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`; const { error: uploadError } = await supabase.storage.from('gallery').upload(path, file, { contentType: mimeType, upsert: false }); if (uploadError) throw uploadError; const { data } = supabase.storage.from('gallery').getPublicUrl(path); const { error } = await supabase.from('gallery').insert({ path, image_url: data.publicUrl, is_public: true }); if (error) throw error; }
export async function createQuote(payload: Record<string, unknown>) { ensureConfig(); const { error } = await supabase.from('leads').insert(payload); if (error) throw error; }