import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, StyleSheet, Text, View } from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import { Card, Loading, Muted, Screen, Title } from '@/src/components/ui';
import { asMoney, clientName } from '@/src/lib/format';
import { getLeads } from '@/src/lib/services';
import { colors } from '@/src/lib/theme';
import type { Lead } from '@/src/types/models';

export default function FinanceScreen() {
  const [leads, setLeads] = useState<Lead[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { setLeads(await getLeads()); } catch (e) { Alert.alert('No se pudo cargar el resumen', e instanceof Error ? e.message : 'Error desconocido'); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const completed = useMemo(() => leads.filter((lead) => lead.status === 'completed'), [leads]); const total = useMemo(() => completed.reduce((sum, lead) => sum + (Number(lead.final_price) || 0), 0), [completed]);
  if (loading) return <Loading />;
  return <Screen><View style={s.header}><Text style={s.kicker}>CONTABILIDAD OPERATIVA</Text><Title>Resumen financiero</Title></View><Card style={s.kpi}><Text style={s.kpiLabel}>TOTAL COBRADO</Text><Text style={s.total}>{asMoney(total)}</Text><Muted>{completed.length} trabajos completados con pago registrado</Muted></Card><View style={s.section}><Text style={s.sectionTitle}>INGRESOS POR CLIENTE</Text></View><FlatList data={completed} keyExtractor={(item) => item.id} contentContainerStyle={s.list} ListEmptyComponent={<Card><Muted>Aún no hay pagos finalizados para contabilizar.</Muted></Card>} renderItem={({ item }) => <Card style={s.row}><View><Title>{clientName(item)}</Title><Muted>{item.created_at ? new Date(item.created_at).toLocaleDateString() : 'Fecha no disponible'}</Muted></View><Text style={s.amount}>{asMoney(item.final_price)}</Text></Card>} ListFooterComponent={<Card style={s.qr}><View style={s.qrText}><Text style={s.sectionTitle}>CÓDIGO QR DE LA EMPRESA</Text><Muted>Muéstralo a clientes para abrir la página de Nieto Green Care LLC.</Muted></View><View style={s.qrBox}><QRCode value="https://nietogreencare.com" size={100} color={colors.background} backgroundColor="#FFFFFF" /></View></Card>} /></Screen>;
}
const s = StyleSheet.create({ header: { padding: 18, gap: 5 }, kicker: { color: colors.gold, fontWeight: '900', letterSpacing: 1.4, fontSize: 11 }, kpi: { marginHorizontal: 14, backgroundColor: colors.forest, gap: 6 }, kpiLabel: { color: '#D1FAE5', fontSize: 12, fontWeight: '900', letterSpacing: 1.2 }, total: { color: colors.gold, fontSize: 38, fontWeight: '900' }, section: { paddingHorizontal: 14, paddingTop: 20, paddingBottom: 9 }, sectionTitle: { color: colors.gold, fontWeight: '900', fontSize: 12, letterSpacing: 1 }, list: { padding: 14, gap: 10 }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, amount: { color: colors.success, fontSize: 17, fontWeight: '900' }, qr: { marginTop: 8, flexDirection: 'row', alignItems: 'center', gap: 12 }, qrText: { flex: 1, gap: 7 }, qrBox: { backgroundColor: '#FFF', padding: 8, borderRadius: 10 } });