import { useCallback, useEffect, useState } from 'react';
import { Alert, FlatList, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { Button, Card, Loading, Muted, Screen, Title } from '@/src/components/ui';
import { colors } from '@/src/lib/theme';
import { deleteGalleryItem, getGallery, setGalleryPublic, uploadGallery } from '@/src/lib/services';
import type { GalleryItem } from '@/src/types/models';

export default function GalleryScreen() {
  const [items, setItems] = useState<GalleryItem[]>([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false);
  const load = useCallback(async () => { try { setItems(await getGallery()); } catch (e) { Alert.alert('No se pudo cargar la galería', e instanceof Error ? e.message : 'Error desconocido'); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const pick = async (camera: boolean) => { const permission = camera ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert('Permiso requerido', 'Autoriza el acceso para cargar una foto.'); const result = camera ? await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: 0.8 }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.8 }); if (result.canceled) return; setUploading(true); try { await uploadGallery(result.assets[0].uri, result.assets[0].mimeType ?? 'image/jpeg'); await load(); } catch (e) { Alert.alert('No se pudo subir la foto', e instanceof Error ? e.message : 'Error desconocido'); } finally { setUploading(false); } };
  const toggle = async (item: GalleryItem) => { try { await setGalleryPublic(item.id, !(item.is_public ?? item.public ?? true)); await load(); } catch (e) { Alert.alert('No se pudo cambiar la visibilidad', e instanceof Error ? e.message : 'Error desconocido'); } };
  const remove = (item: GalleryItem) => Alert.alert('Eliminar foto', 'Esta acción eliminará la imagen y su registro.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Eliminar', style: 'destructive', onPress: () => void deleteGalleryItem(item).then(load).catch((e: unknown) => Alert.alert('Error', e instanceof Error ? e.message : 'Error desconocido')) }]);
  if (loading) return <Loading />;
  return <Screen><View style={s.actions}><Button label={uploading ? 'Subiendo…' : 'Tomar foto'} disabled={uploading} onPress={() => void pick(true)} /><Button label="Subir imagen" variant="outline" disabled={uploading} onPress={() => void pick(false)} /></View><FlatList data={items} numColumns={2} keyExtractor={(item) => item.id} contentContainerStyle={s.grid} columnWrapperStyle={items.length > 1 ? s.row : undefined} ListEmptyComponent={<Card><Title>Galería vacía</Title><Muted>Documenta los trabajos terminados desde el campo.</Muted></Card>} renderItem={({ item }) => <Card style={s.tile}><Image source={{ uri: item.image_url ?? item.url ?? '' }} style={s.image} /><Text numberOfLines={1} style={s.caption}>{item.caption ?? 'Trabajo Nieto Green Care'}</Text><View style={s.tileActions}><Pressable onPress={() => void toggle(item)}><Text style={s.link}>{(item.is_public ?? item.public ?? true) ? 'Ocultar' : 'Publicar'}</Text></Pressable><Pressable onPress={() => remove(item)}><Text style={s.delete}>Eliminar</Text></Pressable></View></Card>} /></Screen>;
}
const s = StyleSheet.create({ actions: { flexDirection: 'row', gap: 10, padding: 14 }, grid: { padding: 14, gap: 12 }, row: { gap: 12 }, tile: { flex: 1, maxWidth: '48%', padding: 8, gap: 8 }, image: { width: '100%', aspectRatio: 1, backgroundColor: colors.elevated, borderRadius: 10 }, caption: { color: colors.text, fontSize: 12, fontWeight: '700' }, tileActions: { flexDirection: 'row', justifyContent: 'space-between' }, link: { color: colors.gold, fontSize: 11, fontWeight: '800' }, delete: { color: colors.danger, fontSize: 11, fontWeight: '800' } });