import { useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Button, Card, Muted, Screen, styles as ui, Title } from '@/src/components/ui';
import { colors } from '@/src/lib/theme';
import { createQuote } from '@/src/lib/services';

const services = ['Tree & Bush Trimming', 'Sod Installation', 'Flower Beds', 'Fertilizer', 'Gravel & Rock Installation', 'Metal Edging', 'Mulch', 'Yard Clean Up', 'Top Soil', 'Weekly & Biweekly Lawn Service'];
export default function QuoteScreen() {
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [address, setAddress] = useState(''); const [yards, setYards] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [sending, setSending] = useState(false);
  const submit = async () => { if (!name.trim() || !phone.trim() || !address.trim() || !selected.length) return Alert.alert('Información incompleta', 'Agrega cliente, teléfono, dirección y al menos un servicio.'); setSending(true); try { await createQuote({ client_name: name.trim(), name: name.trim(), phone: phone.trim(), address: address.trim(), yards: yards ? Number(yards) : null, services: selected, status: 'pending' }); Alert.alert('Cotización enviada', 'La solicitud fue creada y ya está disponible en Solicitudes.'); setName(''); setPhone(''); setAddress(''); setYards(''); setSelected([]); } catch (e) { Alert.alert('No se pudo enviar', e instanceof Error ? e.message : 'Error desconocido'); } finally { setSending(false); } };
  return <Screen><ScrollView contentContainerStyle={s.content}><Text style={s.kicker}>COTIZADOR MÓVIL</Text><Title>Nueva solicitud</Title><Card><Text style={ui.label}>CLIENTE</Text><TextInput value={name} onChangeText={setName} style={ui.input} placeholder="Nombre completo" placeholderTextColor={colors.muted} /><Text style={[ui.label, s.top]}>TELÉFONO</Text><TextInput value={phone} onChangeText={setPhone} style={ui.input} keyboardType="phone-pad" placeholder="(000) 000-0000" placeholderTextColor={colors.muted} /><Text style={[ui.label, s.top]}>DIRECCIÓN</Text><TextInput value={address} onChangeText={setAddress} style={ui.input} placeholder="Dirección del trabajo" placeholderTextColor={colors.muted} /><Text style={[ui.label, s.top]}>YARDAS (OPCIONAL)</Text><TextInput value={yards} onChangeText={setYards} style={ui.input} keyboardType="decimal-pad" placeholder="0" placeholderTextColor={colors.muted} /></Card><Card><Text style={ui.section}>SERVICIOS OFICIALES</Text><View style={s.serviceList}>{services.map((service) => { const active = selected.includes(service); return <Button key={service} label={`${active ? '✓ ' : ''}${service}`} variant={active ? 'primary' : 'outline'} onPress={() => setSelected(active ? selected.filter((item) => item !== service) : [...selected, service])} />; })}</View><Muted>Selecciona todos los servicios solicitados por el cliente.</Muted></Card><Button label={sending ? 'Enviando…' : 'Enviar cotización'} disabled={sending} onPress={() => void submit()} /></ScrollView></Screen>;
}
const s = StyleSheet.create({ content: { padding: 14, gap: 12 }, kicker: { color: colors.gold, fontWeight: '900', fontSize: 11, letterSpacing: 1.5 }, top: { marginTop: 12 }, serviceList: { gap: 8, marginBottom: 12 } });