import type { ReactNode } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, type TextProps, View } from 'react-native';
import { colors } from '@/src/lib/theme';

export function Screen({ children }: { children: ReactNode }) { return <View style={styles.screen}>{children}</View>; }
export function Card({ children, style }: { children: ReactNode; style?: object }) { return <View style={[styles.card, style]}>{children}</View>; }
export function Title({ children }: { children: ReactNode }) { return <Text style={styles.title}>{children}</Text>; }
export function Muted({ children, ...props }: TextProps) { return <Text style={styles.muted} {...props}>{children}</Text>; }
export function Button({ label, onPress, variant = 'primary', disabled = false }: { label: string; onPress: () => void; variant?: 'primary' | 'outline' | 'danger'; disabled?: boolean }) { return <Pressable onPress={onPress} disabled={disabled} style={[styles.button, styles[variant], disabled && styles.disabled]}><Text style={[styles.buttonText, variant === 'outline' && styles.outlineText]}>{label}</Text></Pressable>; }
export function Loading() { return <View style={styles.center}><ActivityIndicator color={colors.gold} size="large" /></View>; }
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background }, card: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 16, padding: 14 }, title: { color: colors.text, fontSize: 18, fontWeight: '800' }, muted: { color: colors.muted, fontSize: 13, lineHeight: 19 }, button: { minHeight: 44, paddingHorizontal: 15, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, primary: { backgroundColor: colors.forestLight }, outline: { backgroundColor: 'transparent', borderWidth: 1, borderColor: colors.gold }, danger: { backgroundColor: colors.danger }, buttonText: { color: colors.text, fontWeight: '800', fontSize: 13 }, outlineText: { color: colors.gold }, disabled: { opacity: 0.45 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, input: { backgroundColor: colors.elevated, color: colors.text, borderColor: colors.border, borderWidth: 1, borderRadius: 12, minHeight: 46, paddingHorizontal: 13, fontSize: 15 }, label: { color: colors.muted, fontWeight: '700', marginBottom: 6, fontSize: 12 }, section: { color: colors.gold, fontWeight: '900', letterSpacing: 1, fontSize: 12, marginBottom: 9 }
});